### PR TITLE
Enforce usage of let or const with ESLint's no-var

### PR DESCRIPTION
**Pull request by Siilwyn**
Solves #9

### CODE REVIEW

**Comment by bheart** [comment]
Those can all be `const`, no? If so, I would probably bind them as such.

**Comment by xCausxn** [comment]
Use const all the time,  unless you need to change the variable which is when you use let

**Comment by Siilwyn** [comment]
Yes I know, sorry about that, was in a hurry when I did this and just used ESLint's `--fix` capability. :)

Should be good now.

**Comment by bheart** [comment]
LGTM

**Pull request merged**
